//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertable
    {
        public int User_id { get; set; }
        public string Username { get; set; }
        public string passwordd { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Phonenumber { get; set; }
        public string city { get; set; }
    }
}
